name: Soft update (only changes)

inputs:
  ODOO_SERVICE:
    type: string
    required: true
  USE_VENV:
    type: string
    requred: true
  SERVER_USER:
    type: string
    requred: true
  PYTHON_SCRIPT:
    type: string
    required: true
  DB_LIST:
    type: string
    required: true
  MAIN_PATH:
    type: string
    required: true
  ODOO_CONFIG:
    type: string
    required: true
  show_log:
    type: boolean
    required: false
    default: false
  base_update:
    type: boolean
      required: false
      default: false

runs:
  using: 'composite'
  steps:
    - name: Update Databases
      run: |
        echo -e "::group::\033[34m=== Starting database update ===\033[0m"
        venv_flag=$([ "$USE_VENV" == "true" ] && echo "--use-venv" || echo "")
        showlog_flag=$([ "$SHOW_LOG" == "true" ] && echo "--show-log" || echo "")
        hard_flag=$([ "$HARD_UPD" == "true" ] && echo "--hard" || echo "")

        trap ' \
          echo "::endgroup::" \
        ' EXIT

        sudo -u $SERVER_USER $PYTHON_SCRIPT \
          --databases "$DB_LIST" \
          --main_path "$MAIN_PATH" \
          --config "$ODOO_CONFIG" \
          --user "$SERVER_USER" \
          $venv_flag \
          $showlog_flag \
          $hard_flag

      env:
        ODOO_SERVICE: ${{ inputs.ODOO_SERVICE }}
        USE_VENV: ${{ inputs.USE_VENV }}
        SERVER_USER: ${{ inputs.SERVER_USER }}
        PYTHON_SCRIPT: ${{ inputs.PYTHON_SCRIPT }}
        DB_LIST: ${{ inputs.DB_LIST }}
        ODOO_CONFIG: ${{ inputs.ODOO_CONFIG }}
        MAIN_PATH: ${{ inputs.MAIN_PATH }}
        SHOW_LOG: ${{ inputs.show_log }}
        HARD_UPD: ${{ inputs.base_update }}
      shell: bash

