name: Hard update (base module)

inputs:
  ODOO_SERVICE:
    type: string
    required: true
  USE_VENV:
    type: string
    requred: true
  SERVER_USER:
    type: string
    requred: true
  PYTHON_SCRIPT:
    type: string
    required: true
  DB_LIST:
    type: string
    required: true
  MAIN_PATH:
    type: string
    required: true
  ODOO_CONFIG:
    type: string
    required: true
  show_log:
    type: boolean
    required: false
    default: false

runs:
  using: 'composite'
  steps:
    - name: Log step
      run: echo -e "\033[32m=== Starting parallel database update ===\033[0m"
      shell: bash

    - name: Stop Odoo
      run: |
        echo -e "\033[34m=== STOPPING ODOO ===\033[0m"
        sudo systemctl stop $ODOO_SERVICE
        sleep 10
      env:
        ODOO_SERVICE: ${{ inputs.ODOO_SERVICE }}
      shell: bash

    - name: Hard update (base module)
      id: update-database
      run: |
        echo -e "::group::\033[34m=== Starting database update ===\033[0m"
        venv_flag=$([ "$USE_VENV" == "true" ] && echo "--use-venv" || echo "")
        showlog_flag=$([ "$SHOW_LOG" == "true" ] && echo "--show-log" || echo "")
        sudo -u $SERVER_USER $PYTHON_SCRIPT --databases "$DB_LIST" --main_path "$MAIN_PATH" --config "$ODOO_CONFIG" --user "$SERVER_USER" --hard $venv_flag $showlog_flag
        update_status=$?
        echo "UPDATE_RESULT=$update_status" >> $GITHUB_OUTPUT
        echo -e '\033[32mUpdate status ===>' $update_status '\033[0m'
        echo "::endgroup::"
      env:
        USE_VENV: ${{ inputs.USE_VENV }}
        SERVER_USER: ${{ inputs.SERVER_USER }}
        PYTHON_SCRIPT: ${{ inputs.PYTHON_SCRIPT }}
        DB_LIST: ${{ inputs.DB_LIST }}
        ODOO_CONFIG: ${{ inputs.ODOO_CONFIG }}
        MAIN_PATH: ${{ inputs.MAIN_PATH }}
        SHOW_LOG: ${{ inputs.show_log }}
      shell: bash

    - name: Start Odoo
      run: |
        sudo systemctl start $ODOO_SERVICE
        sleep 10
        echo -e "\033[34m=== SHOW ODOO STATUS ===\033[0m"
        sudo systemctl status $ODOO_SERVICE
        if [ $UPDATE_RESULT -ne 0 ]; then
          echo -e "\033[31mError: Database update failed.\033[0m"
          exit 1
        fi
      env:
        ODOO_SERVICE: ${{ inputs.ODOO_SERVICE }}
        UPDATE_RESULT: ${{ steps.update-database.outputs.UPDATE_RESULT }}
      shell: bash
      if: ${{ always() }}
