name: Hard update (base module)

inputs:
  ODOO_SERVICE:
    type: string
    required: true
  USE_VENV:
    type: string
    requred: true
  SERVER_USER:
    type: string
    requred: true
  PYTHON_SCRIPT:
    type: string
    required: true
  DB_LIST:
    type: string
    required: true
  MAIN_PATH:
    type: string
    required: true
  ODOO_CONFIG:
    type: string
    required: true
  show_log:
    type: boolean
    required: false
    default: false

runs:
  using: 'composite'
  steps:
    - name: Hard update (base module)
      run: |
        echo -e "::group::\033[32m=== Starting parallel database update ===\033[0m"
        echo -e "\033[34m=== STOPPING ODOO ===\033[0m"
        sudo systemctl stop $ODOO_SERVICE && sleep 10

        echo -e "\033[34m=== Starting database update ===\033[0m"
        venv_flag=$([ "$USE_VENV" == "true" ] && echo "--use-venv" || echo "")
        sudo -u $SERVER_USER $PYTHON_SCRIPT --databases "$DB_LIST" --main_path "$MAIN_PATH" --config "$ODOO_CONFIG" --user "$SERVER_USER" --hard $venv_flag --show_log $show_log
        update_status=$?

        sudo systemctl start $ODOO_SERVICE && sleep 10
        echo -e "\033[34m=== SHOW STATUS ODOO ===\033[0m"
        sudo systemctl status $ODOO_SERVICE
        echo "::endgroup::"
        if [ $update_status -ne 0 ]; then
          echo -e "\033[31mError: Database update failed.\033[0m"
          exit 1
        fi
      env:
        ODOO_SERVICE: ${{ inputs.ODOO_SERVICE }}
        USE_VENV: ${{ inputs.USE_VENV }}
        SERVER_USER: ${{ inputs.SERVER_USER }}
        PYTHON_SCRIPT: ${{ inputs.PYTHON_SCRIPT }}
        DB_LIST: ${{ inputs.DB_LIST }}
        ODOO_CONFIG: ${{ inputs.ODOO_CONFIG }}
        MAIN_PATH: ${{ inputs.MAIN_PATH }}
        show_log: ${{ inputs.show_log }}
      shell: bash
