name: Soft update (only changes)

inputs:
  ODOO_SERVICE:
    type: string
    required: true
  USE_VENV:
    type: string
    requred: true
  SERVER_USER:
    type: string
    requred: true
  PYTHON_SCRIPT:
    type: string
    required: true
  DB_LIST:
    type: string
    required: true
  MAIN_PATH:
    type: string
    required: true
  ODOO_CONFIG:
    type: string
    required: true
  exclusive_update:
    description: 'Turn off database during update'
    required: false
    default: false
    type: boolean

runs:
  using: 'composite'
  steps:
    - name: Soft update (only changes)
      run: |
        echo -e "::group::\033[32m=== Starting parallel database update ===\033[0m"
        sudo systemctl stop $ODOO_SERVICE

        if [ $exclusive_update == "false" ]; then
          sudo systemctl start $ODOO_SERVICE
        fi

        sleep 10

        venv_flag=$([ "$USE_VENV" == "true" ] && echo "--use-venv" || echo "")
        sudo -u $SERVER_USER $PYTHON_SCRIPT --databases "$DB_LIST" --main_path "$MAIN_PATH" --config "$ODOO_CONFIG" --user "$SERVER_USER" $venv_flag
        update_status=$?

        sudo systemctl restart $ODOO_SERVICE

        echo "::endgroup::"
        if [ $update_status -ne 0 ]; then
          echo -e "\033[31mError: Database update failed.\033[0m"
          exit 1
        fi
      env:
        ODOO_SERVICE: ${{ inputs.ODOO_SERVICE }}
        USE_VENV: ${{ inputs.USE_VENV }}
        SERVER_USER: ${{ inputs.SERVER_USER }}
        PYTHON_SCRIPT: ${{ inputs.PYTHON_SCRIPT }}
        DB_LIST: ${{ inputs.DB_LIST }}
        ODOO_CONFIG: ${{ inputs.ODOO_CONFIG }}
        MAIN_PATH: ${{ inputs.MAIN_PATH }}
        exclusive_update: ${{ inputs.exclusive_update }}
      shell: bash
