name: Install UPDATE_ODOO.PY script

inputs:
  CICD_TOKEN:
    required: true
outputs:
  PYTHON_SCRIPT:
    value: ${{ steps.create-python-script.outputs.PYTHON_SCRIPT }}

runs:
  using: 'composite'
  steps:
    - name: Log checkout
      run: echo -e "\033[32m============= PULLING THE CICD REPO =============\033[0m"
      shell: bash

    - uses: actions/checkout@v4.2.2
      with:
        repository: biko-solutions/cicd_workflows
        token: ${{ inputs.CICD_TOKEN }}
        fetch-depth: 0
        show-progress: false

    - name: Setup update script on remote node
      id: create-python-script
      run: |
        echo -e "\033[32m============= INSTALLING UPDATE SCRIPT =============\033[0m"
        DIR="/tmp/odoo_script_$(date +'%d_%m_%Y_%H_%M_%S')"
        echo "SCRIPTDIR=$DIR" >> $GITHUB_ENV
        ssh deploy bash -c "mkdir -p \"$DIR\""
        scp ./scripts/update_odoo.py deploy:"$DIR/update_odoo.py"
        ssh deploy bash -c "cd \"$DIR\" && python3 -m venv venv"
        ssh deploy bash -c "ls -la \"$DIR\""
        echo "PYTHON_SCRIPT=\"$DIR/venv/bin/python3 $DIR/scripts/update_odoo.py\"" >> $GITHUB_OUTPUT
      shell: bash
