name: Get ODOO logfile

inputs:
  MAIN_PATH:
    required: true
    type: string
  SERVER_USER:
    required: true
    type: string
  SERVER_ADDR:
    required: true
    type: string
  SSH_PORT:
    required: false
    default: 22
    type: string
  SERVER_SSH:
    requred: true

runs:
  using: 'composite'
  steps:
    - name: Configure SSH
      uses: biko-solutions/cicd_workflows/.github/actions/github-runner/common/setup-ssh@main
      with:
        SERVER_SSH: ${{inputs.SERVER_SSH}}
        SERVER_ADDR: ${{inputs.SERVER_ADDR}}
        SERVER_USER: ${{inputs.SERVER_USER}}
        SSH_PORT: ${{inputs.SSH_PORT}}

    - name: Get LOG file
      run: |
        mkdir -p /tmp/artifacts
        scp deploy:$MAIN_PATH/odoo-server.log /tmp/artifacts/odoo-server.log
      shell: bash
      env:
        MAIN_PATH: ${{inputs.MAIN_PATH}}

    - name: Upload as Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: odoo-server-log
        path: /tmp/artifacts/odoo-server.log
