name: Get database list

inputs:
  MAIN_PATH:
  SERVER_USER:
  ODOO_CONFIG:
  USE_VENV:
  ODOO_DB:

outputs:
  DB_RESULT:
    value: ${{ steps.get-db-list.outputs.DB_RESULT }}

runs:
  using: 'composite'
  steps:
    - name: Get database list
      id: get-db-list
      run: |
        echo "=== GET DATABASE LIST ==="
        if [[ "$ODOO_DB" == -* ]]; then
          if [[ "$USE_VENV" == "true" ]]; then
            DB_RESULT=$(sudo -u $SERVER_USER bash -c "source '$MAIN_PATH/venv/bin/activate' && click-odoo-listdb -c '$ODOO_CONFIG' | tr '\n' ' '")
          else
            DB_RESULT=$(sudo -u $SERVER_USER bash -c "click-odoo-listdb -c '$ODOO_CONFIG' | tr '\n' ' '")
          fi
        elif [[ -n "$ODOO_DB" ]]; then
            DB_RESULT=$(echo $ODOO_DB | tr ',' ' ')
        else
          if [[ "$USE_VENV" == "true" ]]; then
            DB_RESULT=$(sudo -u $SERVER_USER bash -c "source '$MAIN_PATH/venv/bin/activate' && click-odoo-listdb -c '$ODOO_CONFIG' | tr '\n' ' '")
          else
            DB_RESULT=$(sudo -u $SERVER_USER bash -c "click-odoo-listdb -c '$ODOO_CONFIG' | tr '\n' ' '")
          fi
        fi
        echo "=== DATABASES ==="
        echo "DB_RESULT=$DB_RESULT" >> $GITHUB_OUTPUT
      env:
        MAIN_PATH: ${{ inputs.MAIN_PATH }}
        SERVER_USER: ${{ inputs.SERVER_USER }}
        ODOO_CONFIG: ${{ inputs.ODOO_CONFIG }}
        USE_VENV: ${{ inputs.USE_VENV }}
        ODOO_DB: ${{ inputs.ODOO_DB }}
      shell: bash
