name: Update repository (BIKO Template)

inputs:
  update_simbioz:
    required: true
    type: boolean

runs:
  using: 'composite'
  steps:
    - name: Update from SIMBIOZ repo
      if: ${{ inputs.update_simbioz == 'true' }}
      run: |
        echo ===== Update from SIMBIOZ repo ====
        cd $MAIN_PATH
        sudo -u $SERVER_USER git submodule foreach --recursive git config --local --replace-all safe.directory '*'
        sudo -u $SERVER_USER git submodule foreach --recursive git config --local --add safe.directory '*'
        sudo -u $SERVER_USER git submodule foreach --recursive git reset --hard
        sudo -u $SERVER_USER git submodule foreach --recursive git pull
        sudo -u $SERVER_USER sh odoo_set_icons.sh || true
      shell: bash
    - name: Update from BIKO repo
      run: |
        echo ===== Update from BIKO repo ====
        echo $CUSTOM_PATH
        if [[ -n "$CUSTOM_PATH" ]]; then
          for PTH in {$CUSTOM_PATH}
          do
            if [[ -d "$PTH" ]]; then
              cd "$PTH"
              echo "Current directory: " && pwd
              if [[ $? -eq 0 ]]; then
                git add . && git diff-index --quiet HEAD || (git stash && git stash drop)
                git reset --hard
                git pull
              fi
            else
              echo "No folder $PTH"
            fi
          done
        else
          echo "NO CUSTOM FOLDERS SPECIFIED"
        fi
      shell: bash
